//
//  Created by AYL on 19/8/23.
//

#ifndef _ERROR_
#define _ERROR_


enum Error_Code{
    AES_ENCRYPT_CTX_ERROR=-100,
    AES_ENCRYPT_INIT_ERROR,
    AES_ENCRYPT_UPDATE_ERROR,
    AES_ENCRYPT_FINAL_ERROR,
    AES_ENCRYPT_ERROR,
    AES_ENCRYPT_B64ENCODE_ERROR,
    AES_DECRYPT_CTX_ERROR,
    AES_DECRYPT_INIT_ERROR,
    AES_DECRYPT_DECRYPT_ERROR,
    AES_DECRYPT_FINAL_ERROR,
    AES_DECRYPT_ERROR,
    AES_DECRYPT_B64DECODE_ERROR,
    EC_KEY_INIT_ERROR,
    EC_KEY_GENERATE_ERROR,
    EC_PRIKEY_GENERATE_ERROR,
    EC_PRIKEY_B64ENCDOE_ERROR,
    EC_PUBKEY_B64ENCDOE_ERROR,
    EC_PUBKEY_GENERATE_ERROR,
    EC_KEY_PRIKEY_GENERATE_ERROR,
    EC_KEY_PUBKEY_GENERATE_ERROR,
    EC_SECRET_PRIKEY_GENERATE_ERROR,
    EC_SECRET_PRIKEY_B64DECODE_ERROR,
    EC_SECRET_PUBKEY_B64DECODE_ERROR,
    EC_SECRET_PUBKEY_GENERATE_ERROR,
    EC_SECRET_ECPOINT_GENERATE_ERROR,
    EC_SECRET_GENERATE_ERROR,
    ECDSA_PRIKEY_B64DECODE_ERROR,
    ECDSA_PRIKEY_ECKEY_GENERATE_ERROR,
    ECDSA_PUBKEY_B64DECODE_ERROR,
    ECDSA_PUBKEY_ECKEY_GENERATE_ERROR,
    ECDSA_DO_SIGN_ERROR,
    ECDSA_SIGN_LEN_GENERATE_ERROR,
    ECDSA_SIGN_GENERATE_ERROR,
    ECDSA_SIGN_B64ENCODE_ERROR,
    ECDSA_SIGN_B64DECODE_ERROR,
    ECDSA_SIGN_RECOVER_ERROR,
    ECDSA_DO_VERIFY_ERROR

};

#endif