TARGET := iphone:clang:latest:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = Swizzle

Swizzle_FILES = Swizzle.m
Swizzle_CFLAGS = -fobjc-arc
Swizzle_INSTALL_PATH = /usr/local/lib

include $(THEOS_MAKE_PATH)/library.mk
